config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  get 'contact/index'
  resources :galleries
  resources :products
  resources :meetings
  resources :news_posts
  resources :comments
  get 'about_us/Index'
  resources :events
  resources :members

  resources :events do
    member do
      get :delete
    end
  end
  resources :news_posts do
    member do
      get :delete
    end
  end
  resources :galleries do
    member do
      get :delete
    end
  end
  resources :comments do
    member do
      get :delete
    end
  end
  resources :meetings do
    member do
      get :delete
    end
  end
  resources :products do
    member do
      get :delete
    end
  end
  resources :members do
    member do
      get :delete
    end
  end

  get 'landing/Index'
  root 'landing#Index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :news_post_id, presence: true
  validates :userID, presence: true

  self.primary_key = 'id'
  belongs_to :news_post
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[show edit update destroy]

  # GET / or /comments.json
  def index
    @comment = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html do
          redirect_to "/news_posts/#{@comment.news_post_id}".html_safe, notice: 'Comment was successfully created.'
        end
        format.json { render :show, status: :created, location: @comment }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.html { redirect_to "/comments/new?news_post=#{@comment.news_post_id}".html_safe }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html do
          redirect_to "/news_posts/#{@comment.news_post_id}".html_safe, notice: 'Comment was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @comment = Comment.find(params[:id])
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to '/news_posts/', notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:name, :description, :news_post_id, :userID)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/views/comments/_edit_form.erb
<% if current_user.uid == comment.userID || current_user.uid == "110391296899575374577" %>
  <%= form_with(model: comment) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
      <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
        <div class="card-body"><center>
          <p><em><%= form.label :description %><br><%= form.text_area :description, :rows => 10 %></em></p>
        </center></div>
      </div>
    </div>

    <center>
      <div class="actions">
        <%= form.submit %>
      </div>
    </center>
  <% end %>
  <% else %>
    <center>
    <h1>Not your comment!</h1>
    </center>
  <% end %>

app/views/comments/_form.html.erb
<% if current_user.uid == "110391296899575374577" && !(comment.userID.blank?)  %>
  <%= form_with(model: comment) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
      <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
        <div class="card-body"><center>

          <%= form.label :userID, comment.userID %><%= form.hidden_field :userID, value: comment.userID %><br>
          <%= form.label :name, comment.name %><%= form.hidden_field :name, value: comment.name %>
          <h5 class="card-title"><div class="field"><strong><%= form.label :title %><br><%= form.text_field :title %></strong></div></h5>
          <p><em><%= form.label :description %><br><%= form.text_area :description, :rows => 10 %></em></p>  </center></div>
      </div>
    </div>

    <center>
      <div class="actions">
        <%= form.submit %>
      </div>
    </center>
  <% end %>
<% else %>
  <%= form_with(model: comment) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
      <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
        <div class="card-body"><center>

          User ID: <%= form.label :userID, current_user.uid %><%= form.hidden_field :userID, value: current_user.uid %><br>
          Your name: <%= form.label :name, current_user.full_name %><%= form.hidden_field :name, value: current_user.full_name %><br>
          <% form.label :news_post_id %><%= form.hidden_field :news_post_id, value: params[:news_post] %>
          <p><em><%= form.label :description %><br><%= form.text_area :description, :rows => 10 %></em></p>
        </center></div>
      </div>
    </div>

    <center>
      <div class="actions">
        <%= form.submit %>
      </div>
    </center>
  <% end %>
<% end %>

app/views/comments/delete.html.erb
<% if current_user.uid == @comment.userID  || current_user.uid == "110391296899575374577" %>
  <%= link_to 'Back', news_post_path %>
  <center>
  <div class="news posts delete">
    <h2>Post to be deleted</h2>

    <%= form_for(@comment, :method => 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this comment?</p>
      <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
        <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
          <div class="card-body"><center>
            <p class="card-text"><em><%= @comment.description %></em></p>
          </center></div>
        </div>
      </div>

      <div class="form-buttons">
        <%= f.submit("Delete Comment") %>
      </div>

    <% end %>
  </div>
  </center>
  <% else %>
    <center>
    <h1>Not your comment!</h1>
    <%= link_to 'Back', news_post_path %>
    </center>
  <% end %>

app/views/comments/edit.html.erb
<center>
<h1>Editing Comment!</h1>
</center>

<%= render 'comments/edit_form', comment: @comment %>

<center>
<%= link_to 'Back', "/news_posts/#{@comment.news_post_id}" %>
</center>

app/views/comments/index.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

  </style>
</head>


<p id="notice"><%= notice %></p>
<h1>Comments Feed</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <center>
    <div class="button-container">
        <%= link_to '<button type="button">New Comment</button>'.html_safe, new_comment_path %>
    </div>
  </center>
  <br>
  <tbody>
    <% @comment.each do |comment| %>
      <tr>
        <div class="mx-auto" style="width: 65%; margin-left: auto; margin-right: auto;">
          <div class="card" style="width: 65%; border: 3px solid black; margin-left: auto; margin-right: auto;">
            <div class="card-body" style="padding: 2%"><center>
              <h5 class="card-post-date">Posted on: <%= comment.created_at.strftime("%m-%d-%Y") %></h5>
              <hr><p class="card-text"><em><%= comment.description %></em></p><hr>

              <%= link_to 'Show', comment, :class => "btn btn-primary" %>
              <% if current_user.uid == comment.userID  || current_user.uid == "110391296899575374577" %>
                <%= link_to 'Edit', edit_comment_path(comment), :class => "btn btn-primary" %>
                <%= link_to 'Delete', delete_comment_path(comment), :class => "btn btn-primary" %>
              <% end %>
              <%= link_to 'Reply', comment, :class => "btn btn-primary" %>
            </center></div>
          </div>
        </div>
      </tr>
      <br>
    <% end %>
  </tbody>
</table>
<br>

app/views/comments/new.html.erb
<center>
<h1>New Comment</h1>

<%= render 'comments/form', comment: @comment %>

<%= link_to 'Back', "/news_posts/" %>
</center>

app/views/comments/show.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

  </style>
</head>

<p id="notice"><%= notice %></p>
<br>
<div class="mx-auto" style="width: 65%; margin-left: auto; margin-right: auto;">
  <div class="card" style="width: 65%; border: 3px solid black; margin-left: auto; margin-right: auto;">
    <div class="card-body" style="padding: 2%"><center>
      <h5 class="card-post-date">Posted on: <%= @comment.created_at.strftime("%m-%d-%Y") %></h5>
      <h5 class="card-post-date">Updated on: <%= @comment.updated_at.strftime("%m-%d-%Y") %></h5>
      <hr><p class="card-text"><em><%= @comment.name %></em></p><hr>
      <hr><p class="card-text"><em><%= @comment.description %></em></p><hr>
      <hr><p class="card-text"><em><%= @comment.news_post_id %></em></p><hr>

      <%= link_to 'Show', @comment, :class => "btn btn-primary" %>
      <% if current_user.uid == comment.userID  || current_user.uid == "110391296899575374577" %>
        <%= link_to 'Edit', edit_comment_path(@comment), :class => "btn btn-primary" %>
        <%= link_to 'Delete', delete_comment_path(@comment), :class => "btn btn-primary" %>
      <% end %>
    </center></div>
  </div>
</div>
<center>
  <br><%= link_to 'Back', comments_path %>
</center>