config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  get 'contact/index'
  resources :galleries
  resources :products
  resources :meetings
  resources :news_posts
  resources :comments
  get 'about_us/Index'
  resources :events
  resources :members

  resources :events do
    member do
      get :delete
    end
  end
  resources :news_posts do
    member do
      get :delete
    end
  end
  resources :galleries do
    member do
      get :delete
    end
  end
  resources :comments do
    member do
      get :delete
    end
  end
  resources :meetings do
    member do
      get :delete
    end
  end
  resources :products do
    member do
      get :delete
    end
  end
  resources :members do
    member do
      get :delete
    end
  end

  get 'landing/Index'
  root 'landing#Index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/news_post.rb
# frozen_string_literal: true

class NewsPost < ApplicationRecord
  validates :name, presence: true
  validates :userID, presence: true
  validates :title, presence: true
  validates :description, presence: true

  has_many :comments, dependent: :destroy
end

app/controllers/news_posts_controller.rb
# frozen_string_literal: true

class NewsPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_news_post, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @news_post = NewsPost.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @news_post = NewsPost.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @news_post = NewsPost.new(news_post_params)

    respond_to do |format|
      if @news_post.save
        format.html { redirect_to @news_post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @news_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @NewsPost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @news_post.update(news_post_params)
        format.html { redirect_to @news_post, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @NewsPost.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @news_post = NewsPost.find(params[:id])
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @news_post.destroy
    respond_to do |format|
      format.html { redirect_to news_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news_post
    @news_post = NewsPost.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_post_params
    params.require(:news_post).permit(:title, :description, :userID, :name)
  end
end

app/views/news_posts/_form.html.erb
<% if current_user.uid == "110391296899575374577" && !(news_post.userID.blank?)  %>
  <%= form_with(model: news_post) do |form| %>
    <% if news_post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(news_post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% news_post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
      <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
        <div class="card-body"><center>
          <%= form.label :userID, news_post.userID %><%= form.hidden_field :userID, value: news_post.userID %><br>
          <%= form.label :name, news_post.name %><%= form.hidden_field :name, value: news_post.name %>
          <h5 class="card-title"><div class="field"><strong><%= form.label :title %><br><%= form.text_field :title %></strong></div></h5>
          <p><em><%= form.label :description %><br><%= form.text_area :description, :rows => 10 %></em></p>
        </center></div>
      </div>
    </div>

    <center>
      <div class="actions">
        <%= form.submit %>
      </div>
    </center>
  <% end %>
<% else %>
  <%= form_with(model: news_post) do |form| %>
    <% if news_post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(news_post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% news_post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
      <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
        <div class="card-body"><center>
          User ID: <%= form.label :userID, current_user.uid %><%= form.hidden_field :userID, value: current_user.uid %><br>
          Your name: <%= form.label :name, current_user.full_name %><%= form.hidden_field :name, value: current_user.full_name %>
          <h5 class="card-title"><div class="field"><strong><%= form.label :title %><br><%= form.text_field :title %></strong></div></h5>
          <p><em><%= form.label :description %><br><%= form.text_area :description, :rows => 10 %></em></p>
        </center></div>
      </div>
    </div>

    <center>
      <div class="actions">
        <%= form.submit %>
      </div>
    </center>
  <% end %>
<% end %>

app/views/news_posts/delete.html.erb
<% if current_user.uid == @news_post.userID  || current_user.uid == "110391296899575374577" %>
  <center>
  <div class="news posts delete">
    <h2>Post to be deleted</h2>

    <%= form_for(@news_post, :method => 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this post?</p>
      <div class="mx-auto" style="width: 300px; margin-left: auto; margin-right: auto;">
        <div class="card" style="width: 300px; border: 3px solid black; margin-left: auto; margin-right: auto;">
          <div class="card-body"><center>
            <h3 class="card-title"><strong><%= @news_post.title %></strong></h3>
            <p class="card-text"><em><%= @news_post.description %></em></p>
          </center></div>
        </div>
      </div>

      <div class="form-buttons">
        <%= f.submit("Delete News Post") %>
      </div>

    <% end %>
  </div>
  <%= link_to 'Back', news_posts_path %>
  </center>
<% else %>
  <center>
  <h1>Not your post!</h1>
  <%= link_to 'Back', news_post_path %>
  </center>
<% end %>

app/views/news_posts/edit.html.erb
<center>
  <h1>Editing Post!</h1>
  </center>

  <%= render 'form', news_post: @news_post %>

  <center>
  <%= link_to 'Show', @news_post %> |
  <%= link_to 'Back', news_post_path %>
</center>

app/views/news_posts/index.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

  </style>
</head>


<p id="notice"><%= notice %></p>
<h1>News Feed</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <center>
    <div class="button-container">
        <%= link_to '<button type="button">New Post</button>'.html_safe, new_news_post_path %>
    </div>
  </center>
  <br>
  <tbody>
    <% @news_post.each do |news_post| %>
      <tr>
        <div class="mx-auto" style="width: 65%; margin-left: auto; margin-right: auto;">
          <div class="card" style="width: 65%; border: 3px solid black; margin-left: auto; margin-right: auto;">
            <div class="card-body" style="padding: 2%"><center>
              <h3 class="card-title"><%= news_post.title %></h3>
              <h5 class="card-author"> Posted by: <%= news_post.name %></h5>
              <h5 class="card-post-date">Posted on: <%= news_post.created_at.strftime("%m-%d-%Y") %></h5>
              <hr><p class="card-text"><em><%= news_post.description %></em></p><hr>
              Post has <%= news_post.comments.size %> comment(s) <br>
              <%= link_to 'Show', news_post, :class => "btn btn-primary" %>
              <% if current_user.uid == news_post.userID || current_user.uid == "110391296899575374577" %>
                <%= link_to 'Edit', edit_news_post_path(news_post), :class => "btn btn-primary" %>
                <%= link_to 'Delete', delete_news_post_path(news_post), :class => "btn btn-primary" %>
              <% end %>
            </center></div>
          </div>
        </div>
      </tr>
      <br>
    <% end %>
  </tbody>
</table>

<br>

app/views/news_posts/new.html.erb
<center>
<h1>New Post</h1>

<%= render 'form', news_post: @news_post %>

<%= link_to 'Back', news_posts_path %>
</center>

app/views/news_posts/show.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

    tr:nth-child(even) {
      background-color: #ebf3ff;
    }

    tr:nth-child(odd) {
      background-color: #dbeaff;
    }


  </style>
</head>

<p id="notice"><%= notice %></p>
<br>
<div class="mx-auto" style="width: 65%; margin-left: auto; margin-right: auto;">
  <div class="card" style="width: 65%; border: 3px solid black; margin-left: auto; margin-right: auto;">
    <div class="card-body" style="padding: 2%"><center>
      <h3 class="card-title"><%= @news_post.title %></h3>
      <h5 class="card-author"> Posted by: <%= @news_post.name %></h5>
      <h5 class="card-post-date">Posted on: <%= @news_post.created_at.strftime("%m-%d-%Y") %></h5>
      <hr><p class="card-text"><em><%= @news_post.description %></em></p><hr>

      <% if current_user.uid == @news_post.userID  || current_user.uid == "110391296899575374577" %>
        <%= link_to 'Edit', edit_news_post_path(@news_post), :class => "btn btn-primary" %>
        <%= link_to 'Delete', delete_news_post_path(@news_post), :class => "btn btn-primary" %>
      <% end %>

    </center></div>
  </div>
</div>

<br>

<div class="mx-auto" style="width: 65%; margin-left: auto; margin-right: auto;">
  <div class="card" style="width: 65%; border: 3px solid blue; margin-left: auto; margin-right: auto;">
    <div class="card-body" style="padding: 2%">
      <center>
      <h3 class="card-title">Comments</h3>

        <table class="table table-bordered border-primary">

          <% if @news_post.comments.blank? %>
            <%= "Be the first one to comment!" %>
          <% end %>


          <tbody>
            <% for comment in @news_post.comments %>
            <tr>
              <td> <%= comment.description %> <br> <br>

                    <%= "Posted by " + comment.name + ", on "%>
                    <%= comment.created_at.strftime("%m/%d/%Y at %I:%M%p") %>

                    <% if comment.created_at != comment.updated_at %>
                      <br> <%= "Edited on " + comment.updated_at.strftime("%m/%d/%Y at %I:%M%p") %>
                    <% end %>


                    <br>
                    <% if current_user.uid == comment.userID  || current_user.uid == "110391296899575374577" %>
                      <%= link_to 'Edit', edit_comment_path(comment), id: 1 %>
                      <%= link_to 'Delete', delete_comment_path(comment), id: 2 %>
                      <% end %>
                  </td>
            </tr>
            <% end %>

          </tbody>
        </table>
        <div class="button">
          <%= link_to 'Add New Comment', "/comments/new?news_post=#{@news_post.id}", :class => "btn btn-primary" %>
        </div>
    </center>
  </div>
  </div>
</div>


<center>
  <br><%= link_to 'Back', news_posts_path %>
</center>