config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  get 'contact/index'
  resources :galleries
  resources :products
  resources :meetings
  resources :news_posts
  resources :comments
  get 'about_us/Index'
  resources :events
  resources :members

  resources :events do
    member do
      get :delete
    end
  end
  resources :news_posts do
    member do
      get :delete
    end
  end
  resources :galleries do
    member do
      get :delete
    end
  end
  resources :comments do
    member do
      get :delete
    end
  end
  resources :meetings do
    member do
      get :delete
    end
  end
  resources :products do
    member do
      get :delete
    end
  end
  resources :members do
    member do
      get :delete
    end
  end

  get 'landing/Index'
  root 'landing#Index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :news_post_id, presence: true
  validates :userID, presence: true

  self.primary_key = 'id'
  belongs_to :news_post
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :date_time, presence: true
  validates :location, presence: true
  has_one_attached :photo

  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/models/gallery.rb
# frozen_string_literal: true

class Gallery < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_one_attached :photo

  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :meeting_date, presence: true
  validates :location, presence: true
  has_one_attached :photo

  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  validates :name, presence: true, format: {with: /ni[c|k]/i, message: "Name must be a variation of Nick (must contain \"nic\" or \"nik\")"}
  # validates :description, presence: true
  # validates :birthday, presence: true
  # validates :classification, presence: true
  # validates :major, presence: true
  validates :email, presence: true
  # validates :phone, presence: true
  has_one_attached :photo

  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/models/news_post.rb
# frozen_string_literal: true

class NewsPost < ApplicationRecord
  validates :name, presence: true
  validates :userID, presence: true
  validates :title, presence: true
  validates :description, presence: true

  has_many :comments, dependent: :destroy
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  has_one_attached :photo

  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    return nil unless email =~ /@gmail.com || @tamu.edu\z/

    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end
end

app/controllers/contact_controller.rb
# frozen_string_literal: true

class ContactController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @event = Event.find(params[:id])
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :date_time, :location, :add_req, :photo)
  end
end

app/helpers/about_us_helper.rb
# frozen_string_literal: true

module AboutUsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

module ContactHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/galleries_helper.rb
# frozen_string_literal: true

module GalleriesHelper
end

app/helpers/landing_helper.rb
# frozen_string_literal: true

module LandingHelper
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

module MeetingsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/layouts/_navbar.html.erb
<header>
    <div class='container'>
        <nav>
            <ul>
                <li> Home </li>
                <li> Events </li>
                <li> Meetings </li>
                <li> Contact </li>
            </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Aggie Nickwork</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="/assets/favicon.png"/>

    <style>
      /* Modify the background color */

      .navbar-custom {
          background-color: #500000;
          margin-bottom: 0
      }

      ul.nav li a, ul.nav li a:visited {
        color: white;
      }

      ul.nav li a:hover, ul.nav li a:active {
        color: black;
      }

      ul.nav li.active a {
        color: white;
      }

      .navbar-nav.navbar-center {
          position: absolute;
          transform: translatex(-50%);
      }

      [data-toggle="collapse"] .fa:before {
        content: "\f139";
      }

      [data-toggle="collapse"].collapsed .fa:before {
        content: "\f13a";
      }

    * {
      font-family: "Comic Sans MS", "Comic Sans", cursive;
    }

    </style>

  </head>


  <nav class="navbar navbar-custom navbar-toggleable-md">
    <div class="container-fluid">
      <div class="navbar-header">
        <center>
        <a class="navbar-brand" href="/">
        <%= image_tag ("https://nick-network.s3.us-east-2.amazonaws.com/imgNN.jpg") , class: "img-responsive", width: "25", height: "25" %>
        </a>
        <a href="/">
        <%= image_tag ("https://nick-network.s3.us-east-2.amazonaws.com/OrgName.jpg") %>
        </a>
        </center>
      </div>
      <ul class="nav navbar-nav" style="margin-bottom: 0; margin-left: 0px">
        <li>
          <button class="btn btn-secondarydropdown-toggle"  style="margin-top: 8px;" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon">&#8711</span>
          </button>
        </li>
      </ul>
      <ul class="nav navbar-nav" style="margin-bottom: 0" id="navbarNav">
        <li> <% if !current_user %> <%= link_to "Sign In", user_google_oauth2_omniauth_authorize_path, class:"nav-link" %> <% end %> </li>
        <li> <% if current_user %>  <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link" %> <% end %> </li>
        <li> <%= link_to "Home", landing_Index_path, class:"nav-link"%> </li>
        <li> <%= link_to "About Us", about_us_Index_path, class:"nav-link"%> </li>
        <li> <%= link_to "Events", events_path, class:"nav-link"%> </li>
        <li> <%= link_to "Meetings", meetings_path, class:"nav-link"%> </li>
        <li> <%= link_to "News Feed", news_posts_path, class:"nav-link"%>  </li>
        <li> <%= link_to "Gallery", galleries_path, class:"nav-link"%> </li>
        <li> <%= link_to "Products", products_path, class:"nav-link"%> </li>
        <li> <%= link_to "Contact", contact_index_path, class:"nav-link"%> </li>
        <li> <%= link_to "Members", members_path, class:"nav-link"%> </li>
        <li> <%= link_to "Profile", members_path, class:"nav-link"%> </li>
      </ul>
    </div>
  </nav>


  <body>
    <%= yield %>
  </body>
</html>