config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  get 'contact/index'
  resources :galleries
  resources :products
  resources :meetings
  resources :news_posts
  resources :comments
  get 'about_us/Index'
  resources :events
  resources :members

  resources :events do
    member do
      get :delete
    end
  end
  resources :news_posts do
    member do
      get :delete
    end
  end
  resources :galleries do
    member do
      get :delete
    end
  end
  resources :comments do
    member do
      get :delete
    end
  end
  resources :meetings do
    member do
      get :delete
    end
  end
  resources :products do
    member do
      get :delete
    end
  end
  resources :members do
    member do
      get :delete
    end
  end

  get 'landing/Index'
  root 'landing#Index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  validates :name, presence: true, format: {with: /ni[c|k]/i, message: "Name must be a variation of Nick (must contain \"nic\" or \"nik\")"}
  # validates :description, presence: true
  # validates :birthday, presence: true
  # validates :classification, presence: true
  # validates :major, presence: true
  validates :email, presence: true
  # validates :phone, presence: true
  has_one_attached :photo

  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_member, only: %i[show edit update destroy]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit; end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @member = Member.find(params[:id])
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:name, :description, :birthday, :classification, :major, :email, :phone, :photo)
  end
end

app/views/members/_form.html.erb
<head>
  <style>
    h1 {
      text-align: center;
    }

    .container {
      max-width: 31em;
      margin: 0 auto;
      padding: 20px;
    }

    .bigger-container {
      max-width: 35em;
      margin: 0 auto;
      background-color: #f2f2f2;
    }

    input {
      padding: 12px 20px;
      width: 400px;
      margin: 8px 0;
      box-sizing: border-box;
    }

    input[type=text]:focus {
      background-color: lightgrey;
      word-wrap: break-word;
        word-break: break-all;
    }

    textarea {
      width: 400px;
      height: 100px;
    }


  </style>
</head>
<% if current_user.uid == "110391296899575374577" && !(member.name.blank?) %>
  <div class="bigger-container">
    <div class="container">
    <%= form_with(model: @member) do |form| %>
      <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

          <ul>
            <% member.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="field">
        <b>Your name:</b> <%= form.label :name, member.name %><%= form.text_field :name, value: member.name %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, placeholder: "Enter description.." %>
      </div>

      <div class="field">
        <%= form.label :birthday, "Birthday" %>
        <br>
        <%= form.date_field :birthday %>
      </div>

      <div class="field">
        <%= form.label :classification %>
        <br>
        <%= form.text_field :classification, placeholder: "Enter Classification.." %>
      </div>

      <div class="field">
      <%= form.label :major %>
      <br>
      <%= form.text_field :major, placeholder: "Major.." %>
      </div>

      <div class="field">
      <b>Email:</b> <%= form.label :email, member.email %><%= form.hidden_field :email, value: member.email %>
      </div>

      <div class="field">
      <%= form.label :phone %>
      <br>
      <%= form.number_field :phone, placeholder: "Enter Phone.." %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>

    <% end %>
  </div>
<% else %>
  <div class="bigger-container">
    <div class="container">
    <%= form_with(model: @member) do |form| %>
      <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

          <ul>
            <% member.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="field">
        <b>Your name:</b> <%= form.label :name, current_user.full_name %><%= form.text_field :name, value: current_user.full_name %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, placeholder: "Enter description.." %>
      </div>

      <div class="field">
        <%= form.label :birthday, "Birthday" %>
        <br>
        <%= form.date_field :birthday %>
      </div>

      <div class="field">
        <%= form.label :classification %>
        <br>
        <%= form.text_field :classification, placeholder: "Enter Classification.." %>
      </div>

      <div class="field">
      <%= form.label :major %>
      <br>
      <%= form.text_field :major, placeholder: "Major.." %>
      </div>

      <div class="field">
      <b>Email:</b> <%= form.label :email, current_user.email %><%= form.hidden_field :email, value: current_user.email %>
      </div>

      <div class="field">
      <%= form.label :phone %>
      <br>
      <%= form.number_field :phone, placeholder: "Enter Phone.." %>
      </div>

      <div class="field">
      <b>Profile picture:</b><%= form.file_field :photo %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>

    <% end %>
  </div>
<% end %>

app/views/members/delete.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      text-align: center;
    }

    .css_img {
      width: 100%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

    .del-meeting {
      text-align: center;
    }

  </style>
</head>
<% if current_user.email == @member.email  || current_user.uid == "110391296899575374577" %>
  <p id="notice"><%= notice %></p>

  <h1> Deleting <%= @member.name %> </h1>

  <div class="del-meeting">
    <%= form_for(@member, :method => 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this member?</p>
      <p><%= @member.name %></p>

      <div class="form-buttons">
        <%= f.submit("Delete member") %>
        <%= link_to '<button type="button"> Back </button>'.html_safe, members_path %>
      </div>

    <% end %>
    <br>
    <br>
  </div>

  <div class="container">
          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
              <% if @member.photo.attached? %>
                <%= image_tag(@member.photo, width: 200) %>
              <% else %>
                <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
              <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <p class="card-text"> <%= @member.description %> </p>
                </div>

                <table class="table table-sm">
                  <colgroup>
                    <col span="1" style="width: 28%;">
                    <col span="1" style="width: 72%;">
                  </colgroup>

                  <tbody>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Birthday </th>
                      <td>
                      <% if @member.birthday%>
                        <%= @member.birthday.strftime("%m/%d/%Y") %>
                      <% end %>
                      </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Description </th>
                      <td> <%= @member.description %> </td>
                    </tr>

                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Classification </th>
                      <td> <%= @member.classification %> </td>
                    </tr>

                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Major </th>
                      <td> <%= @member.major %> </td>
                    </tr>

                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> email </th>
                      <td> <%= @member.email %> </td>
                    </tr>

                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> phone </th>
                      <td> <%= @member.phone %> </td>
                    </tr>

                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Created on </th>
                      <td> <%= @member.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Last updated on </th>
                      <td> <%= @member.updated_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
  </div>
  <% else %>
    <center>
    <h1>Not your profile!</h1>
    <%= link_to 'Back', members_path %>
    </center>
  <% end %>

app/views/members/edit.html.erb
<% if current_user.email == @member.email  || current_user.uid == "110391296899575374577" %>
  <h1>Editing Member</h1>

  <%= render 'form', member: @member %>

  <div class="container", style="margin-left: 12em;">
    <%= link_to '<button type="button"> View </button>'.html_safe, @member %>
    <%= link_to '<button type="button"> Back </button>'.html_safe, member_path %>
  </div>
<% else %>
  <center>
  <h1>Not your account!</h1>
  <%= link_to 'Back', members_path %>
  </center>
<% end %>

app/views/members/index.html.erb
<head>
  <style>
    /** {
      font-family: "Comic Sans MS", "Comic Sans", cursive;
    }*/

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .list-group-flush .list-group-item {
      font-size: 15px;
    }

    .css_img {
      border-radius: 2em 0em 0em 2em;
      width: 110%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }


 </style>
</head>

<p id="notice"><%= notice %></p>

<h1>Member</h1>


<div class="button-container">
  <% member_exist = false %>
  <% @members.each do |member| %>
    <% if current_user.email == member.email %>
      <% member_exist = true %>
    <% end %>
  <% end %>
  <% if !member_exist %>
    <%= link_to '<button type="button">Add New Member</button>'.html_safe, new_member_path %>
  <% end %>
</div>


<br>
<div class="container">
  <% @members.each do |member| %>
        <div class="card mb-3" style="border: 3px solid black;">
          <div class="row g-0">
            <div class="col-md-3">
              <% if member.photo.attached? %>
                <%= image_tag(member.photo, width: 200) %>
              <% else %>
                <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title", style="font-size: 19px;"> <%= member.name %> </h5>
              </div>

              <table class="table table-sm">
                <colgroup>
                  <col span="1" style="width: 15%;">
                  <col span="1" style="width: 70%;">
                </colgroup>

                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Classification </th>
                    <td> <%= member.classification %> </td>
                  </tr>

                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Major </th>
                    <td> <%= member.major %> </td>
                  </tr>

                </tbody>
              </table>

              <div class="card-body">
                <%= link_to 'View', member, :class => "btn btn-primary" %>
                <% if current_user.email == member.email || current_user.uid == "110391296899575374577" %>
                  <%= link_to 'Edit', edit_member_path(member), :class => "btn btn-primary"%>
                  <%= link_to 'Destroy', delete_member_path(member), :class => "btn btn-primary"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <br>
  <% end %>
</div>

app/views/members/new.html.erb
<center>
  <h1>New Member</h1>

  <%= render 'form', member: @member %>

  <%= link_to 'Back', members_path %>
</center>

app/views/members/show.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      text-align: center;
    }

    .css_img {
      width: 100%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }


 </style>
</head>

<p id="notice"><%= notice %></p>

<h1> <%= @member.name %> </h1>
<div class="container">
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
            <% if @member.photo.attached? %>
              <%= image_tag(@member.photo, width: 200) %>
            <% else %>
              <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
            <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <p class="card-text"> <%= @member.description %> </p>
              </div>

              <table class="table table-sm">
                <colgroup>
                  <col span="1" style="width: 28%;">
                  <col span="1" style="width: 72%;">
                </colgroup>

                <tbody>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Birthday </th>
                    <td>
                    <% if @member.birthday%>
                      <%= @member.birthday.strftime("%m/%d/%Y") %>
                    <% end %>
                    </td>
                  </tr>

                  <tr>
                  <th scope="row", style="font-weight: normal; color: gray;"> Classification </th>
                  <td> <%= @member.classification %> </td>
                  </tr>

                  <tr>
                  <th scope="row", style="font-weight: normal; color: gray;"> Major </th>
                  <td> <%= @member.major %> </td>
                  </tr>

                  <tr>
                  <th scope="row", style="font-weight: normal; color: gray;"> Email </th>
                  <td> <%= @member.email %> </td>
                  </tr>

                  <tr>
                  <th scope="row", style="font-weight: normal; color: gray;"> Phone </th>
                  <td> <%= @member.phone %> </td>
                  </tr>

                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Created on </th>
                    <td> <%= @member.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Last updated on </th>
                    <td> <%= @member.updated_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="container", style="margin-left: 30em;">
          <% if current_user.email == @member.email || current_user.uid == "110391296899575374577" %>
            <%= link_to '<button type="button"> Edit </button>'.html_safe, edit_member_path(@member) %>
            <%= link_to '<button type="button"> Delete </button>'.html_safe, delete_member_path(@member) %>
          <% end %>
          <%= link_to '<button type="button"> Back </button>'.html_safe, members_path %>
        </div>
</div>